### ISSUE TITLE
SpadesX does not work in NucetoSpades

### ISSUE THREAD

**Issue by X-DE1** [SpadesX/SpadesX#55]
**Describe the bug**
I tried to connect to a server without port forwarding using this build on 12/31/2022 (https://aos.party/jenkins/job/SpadesX/lastSuccessfulBuild/artifact/build/*zip*/build.zip) with this link aos://16777343 and this other aos://192.168.0.6:32887 in NucetoSpades 0.5 | v7.7.7 but it logged me out using any of the links instead OpenSpades 0.1.3 let me log in with any of the links.
Im using Windows 10
Error Text (Screenshot)
![1213123](https://user-images.githubusercontent.com/101435795/210127843-6adec676-5ba4-4447-bb0a-110f78657bc0.jpg)

**Comment by utf-4096** [comment]
This is because NucetoSpades reports itself as being OpenSpades 7.7.7.
SpadesX kicks users with OS versions that arent 0.1.3 or 0.1.5, because they either dont exist, are outdated or uncommon. In this case, 7.7.7 isn't a real version.

The real fix would be for the client developer to make it report as OS 0.1.3/0.1.5 as it should, but I will let the other devs decide what should be done.

**Comment by xtreme8000** [comment]
quick note that the build is from October, 6cc5d99c02e6bb98f11ccf2886dc5041726161c5

**Comment by Haxk20** [comment]
As utf said the real fix here is the client dev actually  reporting the correct version.

Since allowing an unreal version and potentionally allowing hacked clients who decide to report such version im not gonna allow this version.

You can ask the developer of the client to report correct version. The fix will not come from SpadesX. Atleast not right now.
